#!/bin/bash
sudo -i
rm -f ~/Desktop/fedoraquikstart_step_2.sh
sudo dnf in fuse -y
sudo dnf install akmod-nvidia -y
sudo dnf install xorg-x11-drv-nvidia-cuda -y
sleep 5m
wget [filehere] -P ~/Desktop -O fedoraquikstart_step_3.sh
reboot
