#!/bin/bash
rm -f ~/.local/FFS1.5_NV.sh
sudo -i dnf in fuse -y
sudo dnf install akmod-nvidia -y
sudo dnf install xorg-x11-drv-nvidia-cuda -y
echo "Waiting 5 minutes to finish installation. Please be patient; the system will restart when complete."
sleep 5m
echo "~/.local/FFS2.sh" > ~/Desktop/BehrFFS.sh
reboot
