#!/bin/bash
rm -f ~/Desktop/fedoraquikstart_step_2.sh
sudo -i dnf4 group upgrade multimedia -y
sudo dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing -y
sudo dnf upgrade @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
sudo dnf group install sound-and-video -y
sudo dnf install ffmpeg-libs libva libva-utils -y
