#!/bin/bash
dnf in fuse -y
dnf install akmod-nvidia -y
dnf install xorg-x11-drv-nvidia-cuda -y
dnf4 group upgrade multimedia -y
dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing -y
dnf upgrade @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
dnf group install sound-and-video -y
dnf install ffmpeg-libs libva libva-utils openh264 gstreamer1-plugin-openh264 mozilla-openh264 steam lutris telegram git btop vlc gimp blender flatseal quodlibet yt-dlp pdfarranger -y
dnf group install virtualization -y
wget --content-disposition -P /usr/local "https://vencord.dev/download/vesktop/amd64/rpm" | dnf install /usr/local/vesktop-*.rpm -y | rm -f /usr/local/vesktop-*.rpm
dnf config-manager setopt fedora-cisco-openh264.enabled=1
rm -f /usr/lib64/firefox/browser/defaults/preferences/firefox-redhat-default-prefs.js
systemctl enable libvirtd
