#!/bin/bash
sudo -i dnf4 group upgrade multimedia -y
sudo dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing -y
sudo dnf upgrade @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
sudo dnf group install sound-and-video -y
sudo dnf install ffmpeg-libs libva libva-utils -y
sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld -y
sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld -y
sudo dnf swap mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686 -y
sudo dnf swap mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686 -y
sudo dnf install openh264 gstreamer1-plugin-openh264 mozilla-openh264 steam lutris telegram git btop vlc gimp flatseal quodlibet yt-dlp pdfarranger audacity cargo -y
sudo dnf group install virtualization -y
echo "export PATH=$PATH:~/.cargo/bin/" >> ~/.bashrc
wget --content-disposition -P ~/Downloads "https://vencord.dev/download/vesktop/amd64/rpm" && sudo dnf install ~/Downloads/vesktop-?.?.?.x86_64.rpm -y && rm -f ~/Downloads/vesktop-?.?.?.x86_64.rpm
sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1 && sudo rm -f /usr/lib64/firefox/browser/defaults/preferences/firefox-redhat-default-prefs.js
sudo systemctl enable libvirtd

# Everything below is for vrchat specifically-

sudo sh -c 'echo -e "[unityhub]\nname=Unity Hub\nbaseurl=https://hub.unity3d.com/linux/repos/rpm/stable\nenabled=1\ngpgcheck=1\ngpgkey=https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key\nrepo_gpgcheck=1" > /etc/yum.repos.d/unityhub.repo'
sudo dnf install dotnet-sdk-8.0 unityhub -y
wget --content-disposition -P ~/Unity/Hub "https://download.unity3d.com/download_unity/887be4894c44/LinuxEditorInstaller/Unity-2022.3.22f1.tar.xz" 
cd ~/Unity/Hub 
tar -xf ~/Unity/Hub/Unity-2022.3.22f1.tar.xz
rm -f ~/Unity/Hub/Unity-2022.3.22f1.tar.xz
dotnet tool install --global vrchat.vpm.cli
echo "export PATH=$PATH:~/.dotnet/tools/" >> ~/.bashrc
export PATH=$PATH:~/.dotnet/tools/
vpm install templates
vpm list unity
cd ~/.local/share/VRChatCreatorCompanion
sed -i 1,3d settings.json
mv settings.json notsettings.notjson

cat << EOF > settings.json
{
  "pathToUnityExe": "/home/$USER/Unity/Hub/Editor/Unity",
  "pathtoUnityHub": "/opt/unityhub/unityhub-bin",
EOF

cat notsettings.notjson >> settings.json
rm -f notsettings.notjson
