#!/bin/bash
rm -f ~/Desktop/fedoraquikstart_step_2.sh
sudo -i dnf4 group upgrade multimedia -y
sudo dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing -y
sudo dnf upgrade @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
sudo dnf group install sound-and-video -y
sudo dnf install ffmpeg-libs libva libva-utils -y
sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld -y
sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld -y
sudo dnf swap mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686 -y
sudo dnf swap mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686 -y
sudo dnf install openh264 gstreamer1-plugin-openh264 mozilla-openh264 steam lutris telegram git btop vlc gimp flatseal quodlibet yt-dlp pdfarranger audacity cargo -y
sudo dnf group install virtualization -y
echo "export PATH=$PATH:~/.cargo/bin/" >> ~/.bashrc
wget --content-disposition -P ~/Downloads "https://vencord.dev/download/vesktop/amd64/rpm" && sudo dnf install ~/Downloads/vesktop-?.?.?.x86_64.rpm -y && rm -f ~/Downloads/vesktop-?.?.?.x86_64.rpm
sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1 && sudo rm -f /usr/lib64/firefox/browser/defaults/preferences/firefox-redhat-default-prefs.js
sudo systemctl enable libvirtd

read -p 'Setup complete! Press enter to finalize.'
reboot
