#!/bin/bash
rm -f ~/.local/FFS.sh
echo "max_parallel_downloads=10" | sudo -i tee -a /etc/dnf/dnf.conf
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
sudo dnf install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release -y
sudo dnf group upgrade core -y
sudo dnf4 group update core -y
sudo dnf -y update
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

if [ -f ~/.local/FFS1.5_NV.sh ] 
then
echo "~/.local/FFS1.5(NV).sh" > ~/Desktop/BehrFFS.sh
else
echo "~/.local/FFS2.sh" > ~/Desktop/BehrFFS.sh
fi

reboot
